### ISSUE TITLE
Figure out "catchier" name

### ISSUE THREAD

**Issue by tienne-B** [TheAgoraProject/dta-spec#10]
From being the "Agora Project" in the _MDR_ to being "dta-spec" as the repo name, the name of this markup has not been adequately named to be interesting and describe this project. I have started giving it the name "DebateXML" but should open this up for more discussion.

Some suggestions:
* DebateXML
* DebateML
* TabTransfer
* TabML
* _more suggestions?_

"XML" is the superset of this markup language, which expands to "eXtensible Markup Language". "ML" stands for "markup language" generally.

**Comment by czlee** [comment]
Not sure if we wrote this anywhere, but "DTA" is meant to stand for "debate tournament archive" (so named because the XML spec is meant to be for archives). I'm not sure how important the name is, though: "XML" isn't that catchy, and it caught on fine 😉

**Comment by tienne-B** [comment]
Repo renamed, and documentation reflects new name **DebateXML**.
