### ISSUE TITLE
How to handle conflicts

### ISSUE THREAD

**Issue by tienne-B** [TheAgoraProject/dta-spec#7]
And whether it should be available.

For private use of the format and partial tournaments, it would be good to be able to keep the conflicts/constraints intact.

**Comment by philipbelesky** [comment]
I'd worry about the (even small) risk of the being accidentally disclosed might not be with the upside here. Given conflicts are usually only disclosed for a specific event, or at least to a specific platform, I'm not sure they fit within the remit of an exchange/archive format. There's also a pretty big disparity between how platforms interpret conflicts to the point where they likely wouldn't translate across well.

**Comment by czlee** [comment]
Yeah, I agree. I'd rather not build in the functionality, or at least save this until much after the first version of the standard is in common use and we have a better understanding of what people do with it in practice. I don't think the risk is that small; you wouldn't know whether there was conflict information in a file without opening it, and humans make mistakes when they attach files to emails.
