### ISSUE TITLE
Inclusion of participant email addresses

### ISSUE THREAD

**Issue by tienne-B** [TheAgoraProject/dta-spec#9]
Email addresses form a more-reliable standard identifier for participants due to problems with names, such as having many variants between tournaments, and people with the same name, _etc._. For shared tournament platforms (_i.e._ Tabbie2), emails are used to associate participants with users. This would be important if DebateXML import is added to such platforms. However, there is a potential privacy consideration (like for #7) if such data is included in the format.

**Comment by philipbelesky** [comment]
If the purpose here is to match a unique ID on import, maybe the email could be hashed in some fashion so it's not available in an easily human/machine readable form? Also in practice there are a lot of duplicate accounts with different emails for the same user in similar platforms. As a result emails alone at not a reliable indicator of a unique identity.

**Comment by czlee** [comment]
I'd agree on advising against trying to use email addresses as a unique identifier. It's certainly not a one-to-one mapping, and it's actually not even reliably one person to many emails: occasionally, people share email accounts (e.g. society accounts used inappropriately to identify people).

I've thought about unique identifiers more generally, and basically I think it's not really practical for people. Any unique and stable identifier requires some sort of centralized coordination system. Someone would have to maintain this, which would make the longevity of the spec dependent on that person sticking around or finding an immediate successor, etc. For individuals I think such a system is nigh on impossible. It'll be easier for collation platforms to have annoying complicated merge mechanisms for detecting similar names, than to coordinate ahead of time. For institutions, I think there's a fighting chance, but it'll still be challenging.

In my head these archives are meant to be for archives, for which I don't think email addresses are desirable. They could be useful if we use this spec to exchange pre-tournament data, but that'd be an expansion of mission. It's worth discussing, but just wanted to say that _currently_, pre-tournament import is outside scope.
